export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const SET_CURRENT_DOCTOR = 'SET_CURRENT_DOCTOR';
export const CLEAR_CURRENT_DOCTOR = 'CLEAR_CURRENT_DOCTOR';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const CLEAR_CURRENT_ADMIN ='CLEAR_CURRENT_ADMIN';
export const SET_CURRENT_FARMACIST = 'SET_CURRENT_FARMACIST';
export const CLEAR_CURRENT_FARMACIST = 'CLEAR_CURRENT_FARMACIST';

